version: "3.8"
services:

    nginx:
        image: nginx
        container_name: 'nginx'
        depends_on:
            - frontend
            - backend
        links:
            - backend
        volumes:
            - shared:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"

    frontend:
        build: frontend/.
        ports:
            - "5000:5000"
        container_name: "frontend"
        volumes:
            - shared:/dist
    
    backend:
        build: ./backend
        container_name: "backend"
        ports:
            - "8081:8081"
    
volumes:
    shared: